
//===-- qlogo/procedures.cpp - Procedures class implementation -------*- C++ -*-===//
//
// Copyright 2017-2024 Jason Sikes
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted under the conditions specified in the
// license found in the LICENSE file in the project root.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file contains the implementation of the Procedures class, which is
/// responsible for organizing all procedures in QLogo: primitives,
/// user-defined, and library.
///
//===----------------------------------------------------------------------===//

#include "workspace/procedures.h"
#include "workspace/library.h"
#include <QApplication>
#include "astnode.h"
#include "cmd_strings.h"
#include "compiler.h"
#include "datum_types.h"
#include "flowcontrol.h"
#include "sharedconstants.h"
#include <QDateTime>
#include <QObject>
#include <cmath>

Procedures::Procedures()
{
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();

    // The procedure table code is generated by util/generate_command_table.py:
#include "workspace/primitivetable.h"
}

std::tuple<int, int, int> Procedures::validateParameters(const DatumPtr &cmd, const DatumPtr &parameterList) const
{
    ListIterator iter = parameterList.listValue()->newIterator();
    std::tuple<int, int, int> retval(0, 0, 0);
    int &minimumInputs = std::get<0>(retval);
    int &defaultInputs = std::get<1>(retval);
    int &maximumInputs = std::get<2>(retval);

    if ( ! iter.elementExists()) return retval;
    DatumPtr param = iter.element();

    // Parameters are defined in the following format, and are processed in the following order:
    // Required Inputs, e.g. :FOO
    // Optional inputs, e.g. [:BAZ 87]
    // Rest input, e.g. [:GARPLY]
    // Default number, e.g. 5

    // Required Inputs, e.g. :FOO
    while (param.isWord())
    {
        ++minimumInputs;
        ++defaultInputs;
        ++maximumInputs;
        QString paramName = param.toString(Datum::ToStringFlags_Key);
        if ((paramName.isEmpty()) || paramName.startsWith(':') || paramName.startsWith('"'))
            throw FCError::doesntLike(cmd, param);

        if ( ! iter.elementExists()) return retval;
        param = iter.element();
    }

    // Optional inputs, e.g. [:BAZ 87]
    while (param.isList() && (param.listValue()->count() > 1))
    {
        ++maximumInputs;
        List *list = param.listValue();
        DatumPtr head = list->head;
        if ( ! head.isWord())
            throw FCError::doesntLike(cmd, param);
        QString paramName = head.toString(Datum::ToStringFlags_Key);
        if ((paramName.isEmpty()) || paramName.startsWith(':') || paramName.startsWith('"'))
            throw FCError::doesntLike(cmd, param);

        if ( ! iter.elementExists()) return retval;
        param = iter.element();
    }

        // Rest input, e.g. [:GARPLY]
    if (param.isList())
    {
        maximumInputs = -1;
        List *list = param.listValue();
        if (list->count() != 1)
            throw FCError::doesntLike(cmd, param);
        DatumPtr head = list->head;
        if ( ! head.isWord())
            throw FCError::doesntLike(cmd, param);

        QString paramName = head.toString(Datum::ToStringFlags_Key);
        if ((paramName.isEmpty()) || paramName.startsWith(':') || paramName.startsWith('"'))
            throw FCError::doesntLike(cmd, param);

        if ( ! iter.elementExists()) return retval;
        param = iter.element();
    }

    // Default number, e.g. 5
    if (param.isWord())
    {
        double paramAsNumber = param.wordValue()->numberValue();
        if ( ! param.wordValue()->numberIsValid)
            throw FCError::doesntLike(cmd, param);

        defaultInputs = paramAsNumber;
        if ((paramAsNumber != floor(paramAsNumber)) || (defaultInputs < minimumInputs)
         || ((defaultInputs > maximumInputs) && (maximumInputs != -1)))
            throw FCError::doesntLike(cmd, param);
    }

    // There should be no more parameters.
    if (iter.elementExists())
        throw FCError::doesntLike(cmd, iter.element());

    return retval;
}

void Procedures::defineProcedure(const DatumPtr &cmd,
                                 const DatumPtr &procnameP,
                                 const DatumPtr &textP,
                                 const QList<DatumPtr> &sourceText)
{
    procnameP.wordValue()->numberValue();
    if (procnameP.wordValue()->numberIsValid)
        throw FCError::doesntLike(cmd, procnameP);

    QString procname = procnameP.toString(Datum::ToStringFlags_Key);

    QChar firstChar = procname[0];
    if ((firstChar == '"') || (firstChar == ':'))
        throw FCError::doesntLike(cmd, procnameP);

    // TODO: We should allow conditional redefinition of procedures, such as after editing.
    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);

    if ( ! textP.isList())
        throw FCError::doesntLike(cmd, textP);

    List *text = textP.listValue();
    if (text->isEmpty())
        throw FCError::doesntLike(cmd, textP);
    DatumPtr parameterList = text->head;
    if ( ! parameterList.isList())
        throw FCError::doesntLike(cmd, parameterList);

    std::tuple<int, int, int> arity = validateParameters(cmd, parameterList);
    QString cmdString = cmd.toString(Datum::ToStringFlags_Key);
    bool isMacro = ((cmdString == QObject::tr(".MACRO")) || (cmdString == QObject::tr(".DEFMACRO")));

    auto *body = new Procedure();
    DatumPtr bodyP(body);
    body->countOfMinParams_ = std::get<0>(arity);
    body->countOfDefaultParams_ = std::get<1>(arity);
    body->countOfMaxParams_ = std::get<2>(arity);
    body->isMacro_ = isMacro;
    body->sourceText_ = sourceText;
    body->instructionList_ = textP;
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();

    procedures_[procname] = bodyP;
}


void Procedures::copyProcedure(const DatumPtr &newnameP, const DatumPtr &oldnameP)
{
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();
    QString newname = newnameP.toString(Datum::ToStringFlags_Key);
    QString oldname = oldnameP.toString(Datum::ToStringFlags_Key);

    if (stringToCmd.contains(newname))
        throw FCError::isPrimitive(newnameP);

    if (stringToCmd.contains(oldname))
    {
        throw FCError::isPrimitive(oldnameP);
    }
    if (isNamedProcedure(oldname))
    {
        procedures_[newname] = procedures_[oldname];
        return;
    }
    throw FCError::noHow(oldnameP);
}

void Procedures::eraseProcedure(const DatumPtr &procnameP)
{
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();

    QString procname = procnameP.toString(Datum::ToStringFlags_Key);
    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);
    procedures_.remove(procname);
}

DatumPtr Procedures::procedureText(const DatumPtr &procnameP) const
{
    QString procname = procnameP.toString(Datum::ToStringFlags_Key);

    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);
    if (!isNamedProcedure(procname))
        throw FCError::noHow(procnameP);
    Procedure *body = procedureForName(procname).procedureValue();


    return body->instructionList_;
}

DatumPtr Procedures::procedureFulltext(const DatumPtr &procnameP, bool shouldValidate) const
{
    const QString procname = procnameP.toString(Datum::ToStringFlags_Key);
    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);

    if (isNamedProcedure(procname))
    {
        Procedure *body = procedureForName(procname).procedureValue();

        // If there is no source text, generate it from the instruction list.
        if (body->sourceText_.isEmpty())
        {
            ListBuilder retvalBuilder;
            retvalBuilder.append(DatumPtr(generateProcedureTitleLine(procnameP)));

            ListIterator b = body->instructionList_.listValue()->newIterator();

            while (b.elementExists())
            {
                retvalBuilder.append(DatumPtr(b.element().toString(Datum::ToStringFlags_Show)));
            }

            DatumPtr end(QObject::tr("END"));
            retvalBuilder.append(end);
            return retvalBuilder.finishedList();
        }
        else
        {
            ListBuilder retvalBuilder;
            for (const auto &line : body->sourceText_)
            {
                retvalBuilder.append(line);
            }
            return retvalBuilder.finishedList();
        }
    }
    else if (shouldValidate)
    {
        throw FCError::noHow(procnameP);
    }

    // If there is no procedure by that name, generate an empty procedure.
    ListBuilder retvalBuilder;
    retvalBuilder.append(DatumPtr(QObject::tr("to ") + procnameP.toString()));
    retvalBuilder.append(DatumPtr(QObject::tr("END")));
    return retvalBuilder.finishedList();
}

QString Procedures::generateProcedureTitleLine(const DatumPtr &procnameP) const
{
    QString procname = procnameP.toString(Datum::ToStringFlags_Key);

    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);
    if (!isNamedProcedure(procname))
        throw FCError::noHow(procnameP);

    Procedure *body = procedureForName(procname).procedureValue();

    List *retvalL = body->instructionList_.listValue()->head.listValue();
    retvalL = new List(DatumPtr(procnameP), retvalL);
    DatumPtr cmd = DatumPtr((body->isMacro_) ? QObject::tr(".macro") : QObject::tr("to"));
    retvalL = new List(cmd, retvalL);
    DatumPtr retvalP = DatumPtr(retvalL);
    return retvalP.toString(Datum::ToStringFlags_None);
}

DatumPtr Procedures::procedureForName(const QString &aName) const
{
    if (!procedures_.contains(aName))
    {
        if (!Library::get().allProcedureNames().contains(aName))
        {
            return nothing();
        }
        // TODO: Procedure is in our library, add it to our procedures table.
    }
    Q_ASSERT(procedures_.contains(aName));
    return procedures_[aName];
}

bool Procedures::isNamedProcedure(const QString &aName) const
{
    return procedures_.contains(aName) || Library::get().allProcedureNames().contains(aName);
}

std::tuple<DatumPtr, int, int, int> Procedures::astnodeFromPrimitive(const DatumPtr &cmdP) const
{
    QString cmdString = cmdP.toString(Datum::ToStringFlags_Key);
    const auto &cmd = stringToCmd.find(cmdString);
    if (cmd == stringToCmd.end())
    {
        return {nothing(), 0, 0, 0};
    }
    const Cmd_t &command = cmd.value();
    auto node = DatumPtr(new ASTNode(cmdP));
    node.astnodeValue()->genExpression_ = command.method_;
    node.astnodeValue()->returnType_ = command.returnType_;
    return {node, command.countOfMinParams_, command.countOfDefaultParams_, command.countOfMaxParams_};
}

std::tuple<DatumPtr, int, int, int> Procedures::astnodeFromProcedure(const DatumPtr &cmdP) const
{
    QString cmdString = cmdP.toString(Datum::ToStringFlags_Key);
    DatumPtr procBody = procedureForName(cmdString);
    if (procBody == nothing())
    {
        return {nothing(), 0, 0, 0};
    }
    auto node = DatumPtr(new ASTNode(cmdP));

    // TODO: decide what to do here after we refactor the evaluator.
    // if (procBody.procedureValue()->isMacro)
    //     node.astnodeValue()->genExpression = &Compiler::genExecMacro;
    // else
    //     node.astnodeValue()->genExpression = &Compiler::genExecProcedure;

    node.astnodeValue()->genExpression_ = &Compiler::genExecProcedure;
    node.astnodeValue()->returnType_ = RequestReturnDN;
    node.astnodeValue()->procedure_ = procBody;
    return {node, procBody.procedureValue()->countOfMinParams_, procBody.procedureValue()->countOfDefaultParams_, procBody.procedureValue()->countOfMaxParams_};
}

std::tuple<DatumPtr, int, int, int> Procedures::astnodeFromCommand(const DatumPtr &cmdP) const
{
    QString cmdString = cmdP.toString(Datum::ToStringFlags_Key);

    auto [node, minParams, defaultParams, maxParams] = astnodeFromPrimitive(cmdP);
    if (node != nothing())
    { // This is a primitive.
        return {node, minParams, defaultParams, maxParams};
    }
    
    auto [procNode, procMinParams, procDefaultParams, procMaxParams] = astnodeFromProcedure(cmdP);
    if (procNode.isNothing())
    {
        // This is not a command.
        throw FCError::noHow(cmdP);
    }

    // This is a procedure.
    return {procNode, procMinParams, procDefaultParams, procMaxParams};
    // TODO: Foo and setFoo
}

DatumPtr Procedures::astnodeWithLiterals(const DatumPtr &cmd, const DatumPtr &params)
{
    auto [node, minParams, defaultParams, maxParams] = astnodeFromCommand(cmd);

    int countOfChildren = params.listValue()->count();
    if (countOfChildren < minParams)
        throw FCError::notEnoughInputs(cmd);
    if ((countOfChildren > maxParams) && (maxParams != -1))
        throw FCError::tooManyInputs(cmd);

    ListIterator iter = params.listValue()->newIterator();
    while (iter.elementExists())
    {
        DatumPtr p = iter.element();
        auto datumNode = DatumPtr(new ASTNode(QObject::tr("literal")));
        datumNode.astnodeValue()->genExpression_ = &Compiler::genLiteral;
        datumNode.astnodeValue()->addChild(p);
        node.astnodeValue()->addChild(datumNode);
    }
    return node;
}

bool Procedures::isProcedure(const QString &procname) const
{
    if (stringToCmd.contains(procname) || procedures_.contains(procname))
        return true;
    return false;
}

bool Procedures::isMacro(const QString &procname) const
{
    if (procedures_.contains(procname))
    {
        DatumPtr procedure = procedures_[procname];
        return procedure.procedureValue()->isMacro_;
    }
    return false;
}

bool Procedures::isPrimitive(const QString &procname) const
{
    return (stringToCmd.contains(procname));
}

bool Procedures::isDefined(const QString &procname) const
{
    return (procedures_.contains(procname));
}

DatumPtr Procedures::allProcedureNames() const
{
    ListBuilder retvalBuilder;
    for (const auto &iter : procedures_.asKeyValueRange())
    {
        retvalBuilder.append(DatumPtr(iter.first));
    }
    return retvalBuilder.finishedList();
}

DatumPtr Procedures::allPrimitiveProcedureNames() const
{
    ListBuilder retvalBuilder;
    for (const auto &iter : stringToCmd.asKeyValueRange())
    {
        retvalBuilder.append(DatumPtr(iter.first));
    }
    return retvalBuilder.finishedList();
}

DatumPtr Procedures::arity(const DatumPtr &nameP) const
{
    int minParams, defParams, maxParams;
    QString procname = nameP.toString(Datum::ToStringFlags_Key);

    if (procedures_.contains(procname))
    {
        DatumPtr command = procedures_[procname];
        minParams = command.procedureValue()->countOfMinParams_;
        defParams = command.procedureValue()->countOfDefaultParams_;
        maxParams = command.procedureValue()->countOfMaxParams_;
    }
    else if (stringToCmd.contains(procname))
    {
        Cmd_t command = stringToCmd[procname];
        minParams = command.countOfMinParams_;
        defParams = command.countOfDefaultParams_;
        maxParams = command.countOfMaxParams_;
    }
    else
    {
        throw FCError::noHow(nameP);
    }

    ListBuilder retvalBuilder;
    retvalBuilder.append(DatumPtr(minParams));
    retvalBuilder.append(DatumPtr(defParams));
    retvalBuilder.append(DatumPtr(maxParams));
    return retvalBuilder.finishedList();
}
