
//===-- qlogo/procedures.cpp - Procedures class implementation -------*- C++ -*-===//
//
// Copyright 2017-2024 Jason Sikes
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted under the conditions specified in the
// license found in the LICENSE file in the project root.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file contains the implementation of the Procedures class, which is
/// responsible for organizing all procedures in QLogo: primitives,
/// user-defined, and library.
///
//===----------------------------------------------------------------------===//

#include "workspace/procedures.h"
#include <QApplication>
#include "astnode.h"
#include "cmd_strings.h"
#include "compiler.h"
#include "datum_types.h"
#include "flowcontrol.h"
#include "sharedconstants.h"
#include <QDateTime>
#include <QObject>
#include <cmath>

Procedures::Procedures()
{
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();

    // The procedure table code is generated by util/generate_command_table.py:
#include "workspace/primitivetable.h"
}

void Procedures::defineProcedure(const DatumPtr &cmd,
                                 const DatumPtr &procnameP,
                                 const DatumPtr &text,
                                 const QList<DatumPtr> &sourceText)
{
    procnameP.wordValue()->numberValue();
    if (procnameP.wordValue()->numberIsValid)
        throw FCError::doesntLike(cmd, procnameP);

    QString procname = procnameP.toString(Datum::ToStringFlags_Key);

    QChar firstChar = procname[0];
    if ((firstChar == '"') || (firstChar == ':'))
        throw FCError::doesntLike(cmd, procnameP);

    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);

    DatumPtr procBody = createProcedure(cmd, text, sourceText);

    procedures_[procname] = procBody;
}

DatumPtr Procedures::createProcedure(const DatumPtr &cmd, const DatumPtr &text, const QList<DatumPtr> &sourceText)
{
    Procedure *body = initializeProcedureBody(cmd, sourceText);
    DatumPtr bodyP(body);

    parseProcedureParameters(cmd, text, body);
    setupInstructionList(text, body);
    processTags(body);

    return bodyP;
}

Procedure* Procedures::initializeProcedureBody(const DatumPtr &cmd, const QList<DatumPtr> &sourceText)
{
    auto *body = new Procedure();
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();

    QString cmdString = cmd.toString(Datum::ToStringFlags_Key);
    bool isMacro = ((cmdString == QObject::tr(".MACRO")) || (cmdString == QObject::tr(".DEFMACRO")));

    body->countOfDefaultParams_ = 0;
    body->countOfMinParams_ = 0;
    body->countOfMaxParams_ = 0;
    body->isMacro_ = isMacro;
    body->sourceText_ = sourceText;

    return body;
}

void Procedures::parseProcedureParameters(const DatumPtr &cmd, const DatumPtr &text, Procedure *body)
{
    bool isOptionalDefined = false;
    bool isRestDefined = false;
    bool isDefaultDefined = false;

    // Parameters are defined in the following format, and are processed in the following order:
    // Required Inputs, e.g. :FOO
    // Optional inputs, e.g. [:BAZ 87]
    // Rest input, e.g. [:GARPLY]
    // Default number, e.g. 5

    ListIterator paramIter = text.listValue()->head.listValue()->newIterator();

    while (paramIter.elementExists())
    {
        DatumPtr currentParam = paramIter.element();

        if (currentParam.isWord())
        {
            processWordParameter(cmd, currentParam, body, isOptionalDefined, isRestDefined, isDefaultDefined);
        }
        else if (currentParam.isList())
        {
            processListParameter(cmd, currentParam, body, isOptionalDefined, isRestDefined, isDefaultDefined);
        }
        else
        {
            throw FCError::doesntLike(cmd, currentParam);
        }
    }
}

void Procedures::processWordParameter(const DatumPtr &cmd, const DatumPtr &currentParam, Procedure *body,
                                      bool &isOptionalDefined, bool &isRestDefined, bool &isDefaultDefined)
{
    // This is a default number, or a required input.
    double paramAsNumber = currentParam.wordValue()->numberValue();
    if (currentParam.wordValue()->numberIsValid)
    {
        // This is a default number, e.g. 5
        if (isDefaultDefined)
            throw FCError::doesntLike(cmd, currentParam);

        bool isNotInteger = (paramAsNumber != floor(paramAsNumber));
        bool isBelowMinimum = (paramAsNumber < body->countOfMinParams_);
        bool isAboveMaximum = (body->countOfMaxParams_ >= 0) && 
                                  (paramAsNumber > body->countOfMaxParams_);
        if (isNotInteger || isBelowMinimum || isAboveMaximum)
            throw FCError::doesntLike(cmd, currentParam);
        body->countOfDefaultParams_ = paramAsNumber;
        isDefaultDefined = true;
    }
    else
    {
        // This is a required input, e.g. :FOO
        if (isDefaultDefined || isRestDefined || isOptionalDefined)
            throw FCError::doesntLike(cmd, currentParam);
        QString paramName = currentParam.toString(Datum::ToStringFlags_Key);
        if (paramName.startsWith(':') || paramName.startsWith('"'))
            paramName.remove(0, 1);
        if (paramName.size() < 1)
            throw FCError::doesntLike(cmd, currentParam);
        body->requiredInputs_.append(paramName);
        body->countOfDefaultParams_ += 1;
        body->countOfMinParams_ += 1;
        body->countOfMaxParams_ += 1;
    }
}

void Procedures::processListParameter(const DatumPtr &cmd, const DatumPtr &currentParam, Procedure *body,
                                      bool &isOptionalDefined, bool &isRestDefined, bool &isDefaultDefined)
{
    // This is an optional input or a rest input.
    List *paramList = currentParam.listValue();

    if (paramList->isEmpty())
        throw FCError::doesntLike(cmd, currentParam);

    if (paramList->count() == 1)
    {
        // This is a rest input, e.g. [:GARPLY]
        if (isRestDefined)
            throw FCError::doesntLike(cmd, currentParam);
        DatumPtr param = paramList->head;
        if (param.isWord())
        {
            QString restName = param.toString(Datum::ToStringFlags_Key);
            if (restName.startsWith(':') || restName.startsWith('"'))
                restName.remove(0, 1);
            if (restName.size() < 1)
                throw FCError::doesntLike(cmd, param);
            body->restInput_ = restName;
            isRestDefined = true;
            body->countOfMaxParams_ = -1;
        }
        else
        {
            throw FCError::doesntLike(cmd, param);
        }
    }
    else
    {
        // This is an optional input, e.g. [:BAZ 87]
        if (isRestDefined || isDefaultDefined)
            throw FCError::doesntLike(cmd, currentParam);
        DatumPtr param = paramList->head;
        if (param.isWord())
        {
            QString name = param.toString(Datum::ToStringFlags_Key);
            if (name.startsWith(':') || name.startsWith('"'))
                name.remove(0, 1);
            if (name.size() < 1)
                throw FCError::doesntLike(cmd, param);
            body->optionalInputs_.append(name);
            body->optionalDefaults_.append(paramList);
            isOptionalDefined = true;
            body->countOfMaxParams_ += 1;
        }
        else
        {
            throw FCError::doesntLike(cmd, param);
        }
    }
}

void Procedures::setupInstructionList(const DatumPtr &text, Procedure *body)
{
    body->instructionList_ = text.listValue()->tail;
    if (body->instructionList_.isNothing())
        body->instructionList_ = emptyList();
}

void Procedures::processTags(Procedure *body)
{
    // Iterate over the instruction list and add tags to the tagToLine map.
    ListIterator lineIter = body->instructionList_.listValue()->newIterator();
    while (lineIter.elementExists())
    {
        DatumPtr lineP = lineIter.element();
        ListIterator wordIter = lineP.listValue()->newIterator();
        while (wordIter.elementExists())
        {
            DatumPtr d = wordIter.element();
            if (d.isWord() && (d.toString(Datum::ToStringFlags_Key) == QObject::tr("TAG")) && wordIter.elementExists())
            {
                DatumPtr tag = wordIter.element();
                if (tag.isWord())
                {
                    QString param = tag.toString(Datum::ToStringFlags_Key);
                    if ((param.size() > 1) && param[0] == '"')
                    {
                        QString tagName = param.right(param.size() - 1);
                        body->tagToLine_[tagName] = lineP;
                    }
                }
            }
        }
    }
}

void Procedures::copyProcedure(const DatumPtr &newnameP, const DatumPtr &oldnameP)
{
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();
    QString newname = newnameP.toString(Datum::ToStringFlags_Key);
    QString oldname = oldnameP.toString(Datum::ToStringFlags_Key);

    if (stringToCmd.contains(newname))
        throw FCError::isPrimitive(newnameP);

    if (stringToCmd.contains(oldname))
    {
        throw FCError::isPrimitive(oldnameP);
    }
    if (isNamedProcedure(oldname))
    {
        procedures_[newname] = procedures_[oldname];
        return;
    }
    throw FCError::noHow(oldnameP);
}

void Procedures::eraseProcedure(const DatumPtr &procnameP)
{
    lastProcedureCreatedTimestamp_ = QDateTime::currentMSecsSinceEpoch();

    QString procname = procnameP.toString(Datum::ToStringFlags_Key);
    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);
    procedures_.remove(procname);
}

DatumPtr Procedures::procedureText(const DatumPtr &procnameP) const
{
    QString procname = procnameP.toString(Datum::ToStringFlags_Key);

    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);
    if (!isNamedProcedure(procname))
        throw FCError::noHow(procnameP);
    Procedure *body = procedureForName(procname).procedureValue();

    ListBuilder retvalBuilder;
    ListBuilder inputsBuilder;

    // Generate the parameters interface.
    for (auto &i : body->requiredInputs_)
    {
        inputsBuilder.append(DatumPtr(i));
    }

    QList<DatumPtr>::iterator d = body->optionalDefaults_.begin();
    for (auto &i : body->optionalInputs_)
    {
        List *optInput = d->listValue()->tail.listValue();
        ++d;
        inputsBuilder.append(new List(DatumPtr(i), optInput));
    }

    if (body->restInput_ != "")
    {
        auto *restInput = new List(DatumPtr(body->restInput_), EmptyList::instance());
        inputsBuilder.append(DatumPtr(restInput));
    }

    if (body->countOfDefaultParams_ != body->requiredInputs_.size())
    {
        inputsBuilder.append(DatumPtr(body->countOfDefaultParams_));
    }

    retvalBuilder.append(inputsBuilder.finishedList());

    // Generate and append the instruction list.
    ListIterator b = body->instructionList_.listValue()->newIterator();

    while (b.elementExists())
    {
        retvalBuilder.append(b.element());
    }

    return retvalBuilder.finishedList();
}

DatumPtr Procedures::procedureFulltext(const DatumPtr &procnameP, bool shouldValidate) const
{
    const QString procname = procnameP.toString(Datum::ToStringFlags_Key);
    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);

    if (isNamedProcedure(procname))
    {
        Procedure *body = procedureForName(procname).procedureValue();

        // If there is no source text, generate it from the instruction list.
        if (body->sourceText_.isEmpty())
        {
            ListBuilder retvalBuilder;
            retvalBuilder.append(DatumPtr(procedureTitle(procnameP)));

            ListIterator b = body->instructionList_.listValue()->newIterator();

            while (b.elementExists())
            {
                retvalBuilder.append(DatumPtr(b.element().toString(Datum::ToStringFlags_Show)));
            }

            DatumPtr end(QObject::tr("END"));
            retvalBuilder.append(end);
            return retvalBuilder.finishedList();
        }
        else
        {
            ListBuilder retvalBuilder;
            for (const auto &line : body->sourceText_)
            {
                retvalBuilder.append(line);
            }
            return retvalBuilder.finishedList();
        }
    }
    else if (shouldValidate)
    {
        throw FCError::noHow(procnameP);
    }

    // If there is no procedure by that name, generate an empty procedure.
    ListBuilder retvalBuilder;
    retvalBuilder.append(DatumPtr(QObject::tr("to ") + procnameP.toString()));
    retvalBuilder.append(DatumPtr(QObject::tr("END")));
    return retvalBuilder.finishedList();
}

QString Procedures::procedureTitle(const DatumPtr &procnameP) const
{
    QString procname = procnameP.toString(Datum::ToStringFlags_Key);

    if (stringToCmd.contains(procname))
        throw FCError::isPrimitive(procnameP);
    if (!isNamedProcedure(procname))
        throw FCError::noHow(procnameP);

    Procedure *body = procedureForName(procname).procedureValue();

    ListBuilder firstLineBuilder;

    if (body->isMacro_)
        firstLineBuilder.append(DatumPtr(QObject::tr(".macro")));
    else
        firstLineBuilder.append(DatumPtr(QObject::tr("to")));
    firstLineBuilder.append(procnameP);

    QString paramName;

    for (const auto &i : body->requiredInputs_)
    {
        paramName = i;
        paramName.prepend(':');
        firstLineBuilder.append(DatumPtr(paramName));
    }

    for (const auto &i : body->optionalDefaults_)
    {
        firstLineBuilder.append(i);
    }

    paramName = body->restInput_;
    if (paramName != "")
    {
        paramName.push_front(':');
        DatumPtr restInput = new List(DatumPtr(paramName), EmptyList::instance());
        firstLineBuilder.append(restInput);
    }

    if (body->countOfDefaultParams_ != body->requiredInputs_.size())
    {
        firstLineBuilder.append(DatumPtr(body->countOfDefaultParams_));
    }

    QString retval = firstLineBuilder.finishedList().toString(Datum::ToStringFlags_Show);
    return retval;
}

DatumPtr Procedures::procedureForName(const QString &aName) const
{
    if (!procedures_.contains(aName))
    {
        if (!Library::get().allProcedureNames().contains(aName))
        {
            return nothing();
        }
        // TODO: Procedure is in our library, add it to our procedures table.
    }
    Q_ASSERT(procedures_.contains(aName));
    return procedures_[aName];
}

bool Procedures::isNamedProcedure(const QString &aName) const
{
    return procedures_.contains(aName) || Library::get().allProcedureNames().contains(aName);
}

std::tuple<DatumPtr, int, int, int> Procedures::astnodeFromPrimitive(const DatumPtr &cmdP) const
{
    QString cmdString = cmdP.toString(Datum::ToStringFlags_Key);
    const auto &cmd = stringToCmd.find(cmdString);
    if (cmd == stringToCmd.end())
    {
        return {nothing(), 0, 0, 0};
    }
    const Cmd_t &command = cmd.value();
    auto node = DatumPtr(new ASTNode(cmdP));
    node.astnodeValue()->genExpression_ = command.method_;
    node.astnodeValue()->returnType_ = command.returnType_;
    return {node, command.countOfMinParams_, command.countOfDefaultParams_, command.countOfMaxParams_};
}

std::tuple<DatumPtr, int, int, int> Procedures::astnodeFromProcedure(const DatumPtr &cmdP) const
{
    QString cmdString = cmdP.toString(Datum::ToStringFlags_Key);
    DatumPtr procBody = procedureForName(cmdString);
    if (procBody == nothing())
    {
        return {nothing(), 0, 0, 0};
    }
    auto node = DatumPtr(new ASTNode(cmdP));

    // TODO: decide what to do here after we refactor the evaluator.
    // if (procBody.procedureValue()->isMacro)
    //     node.astnodeValue()->genExpression = &Compiler::genExecMacro;
    // else
    //     node.astnodeValue()->genExpression = &Compiler::genExecProcedure;

    node.astnodeValue()->genExpression_ = &Compiler::genExecProcedure;
    node.astnodeValue()->returnType_ = RequestReturnDatum;
    node.astnodeValue()->procedure_ = procBody;
    return {node, procBody.procedureValue()->countOfMinParams_, procBody.procedureValue()->countOfDefaultParams_, procBody.procedureValue()->countOfMaxParams_};
}

std::tuple<DatumPtr, int, int, int> Procedures::astnodeFromCommand(const DatumPtr &cmdP) const
{
    QString cmdString = cmdP.toString(Datum::ToStringFlags_Key);

    auto [node, minParams, defaultParams, maxParams] = astnodeFromPrimitive(cmdP);
    if (node != nothing())
    { // This is a primitive.
        return {node, minParams, defaultParams, maxParams};
    }
    
    auto [procNode, procMinParams, procDefaultParams, procMaxParams] = astnodeFromProcedure(cmdP);
    if (procNode.isNothing())
    {
        // This is not a command.
        throw FCError::noHow(cmdP);
    }

    // This is a procedure.
    return {procNode, procMinParams, procDefaultParams, procMaxParams};
    // TODO: Foo and setFoo
}

DatumPtr Procedures::astnodeWithLiterals(const DatumPtr &cmd, const DatumPtr &params)
{
    auto [node, minParams, defaultParams, maxParams] = astnodeFromCommand(cmd);

    int countOfChildren = params.listValue()->count();
    if (countOfChildren < minParams)
        throw FCError::notEnoughInputs(cmd);
    if ((countOfChildren > maxParams) && (maxParams != -1))
        throw FCError::tooManyInputs(cmd);

    ListIterator iter = params.listValue()->newIterator();
    while (iter.elementExists())
    {
        DatumPtr p = iter.element();
        auto datumNode = DatumPtr(new ASTNode(QObject::tr("literal")));
        datumNode.astnodeValue()->genExpression_ = &Compiler::genLiteral;
        datumNode.astnodeValue()->addChild(p);
        node.astnodeValue()->addChild(datumNode);
    }
    return node;
}

bool Procedures::isProcedure(const QString &procname) const
{
    if (stringToCmd.contains(procname) || procedures_.contains(procname))
        return true;
    return false;
}

bool Procedures::isMacro(const QString &procname) const
{
    if (procedures_.contains(procname))
    {
        DatumPtr procedure = procedures_[procname];
        return procedure.procedureValue()->isMacro_;
    }
    return false;
}

bool Procedures::isPrimitive(const QString &procname) const
{
    return (stringToCmd.contains(procname));
}

bool Procedures::isDefined(const QString &procname) const
{
    return (procedures_.contains(procname));
}

DatumPtr Procedures::allProcedureNames() const
{
    ListBuilder retvalBuilder;
    for (const auto &iter : procedures_.asKeyValueRange())
    {
        retvalBuilder.append(DatumPtr(iter.first));
    }
    return retvalBuilder.finishedList();
}

DatumPtr Procedures::allPrimitiveProcedureNames() const
{
    ListBuilder retvalBuilder;
    for (const auto &iter : stringToCmd.asKeyValueRange())
    {
        retvalBuilder.append(DatumPtr(iter.first));
    }
    return retvalBuilder.finishedList();
}

DatumPtr Procedures::arity(const DatumPtr &nameP) const
{
    int minParams, defParams, maxParams;
    QString procname = nameP.toString(Datum::ToStringFlags_Key);

    if (procedures_.contains(procname))
    {
        DatumPtr command = procedures_[procname];
        minParams = command.procedureValue()->countOfMinParams_;
        defParams = command.procedureValue()->countOfDefaultParams_;
        maxParams = command.procedureValue()->countOfMaxParams_;
    }
    else if (stringToCmd.contains(procname))
    {
        Cmd_t command = stringToCmd[procname];
        minParams = command.countOfMinParams_;
        defParams = command.countOfDefaultParams_;
        maxParams = command.countOfMaxParams_;
    }
    else
    {
        throw FCError::noHow(nameP);
    }

    ListBuilder retvalBuilder;
    retvalBuilder.append(DatumPtr(minParams));
    retvalBuilder.append(DatumPtr(defParams));
    retvalBuilder.append(DatumPtr(maxParams));
    return retvalBuilder.finishedList();
}
