#! /usr/bin/env python3

"""
Generate C++ header and mapping files for QLogo primitive function declarations.

This script generates the primitive mapping files used by the compiler:
- include/primitives.h (function declarations)
- include/workspace/primitivetable.h (mapping table)

Usage:
    generate_primitive_mappings.py
"""

import os
import sys

# Import shared parsing module
from command_parser import (
    get_project_root,
    parse_all_sources,
    name_to_cpp_identifier,
    string_to_enum,
)


# ============================================================================
# Configuration
# ============================================================================

PRIMITIVE_HEADER = "include/primitives.h"
PRIMITIVE_MAPPINGS = "include/workspace/primitivetable.h"
NAMESPACE_NAME = "StringConstants"


# ============================================================================
# File Templates
# ============================================================================

GLOBAL_HEADER = """// DO NOT EDIT THIS FILE!!!

// It was generated by generate_primitive_mappings.py. Any edits to this file will
// not survive long.
"""

GLOBAL_FOOTER = """
"""

PRIMITIVE_HEADER_HEADER = """#ifndef PRIMITIVE_HEADER_H
#define PRIMITIVE_HEADER_H

"""

PRIMITIVE_HEADER_FOOTER = """#endif // PRIMITIVE_HEADER_H
"""

PRIMITIVE_MAPPINGS_HEADER = """
"""

PRIMITIVE_MAPPINGS_FOOTER = """
"""


# ============================================================================
# Generation Functions
# ============================================================================

def write_primitive_entries(entries, method, header_file, table_file):
    """
    Write primitive mapping entries to both output files.
    
    Args:
        entries: List of command entry tuples [name, min, default, max, return_type]
        method: Name of the Compiler method
        header_file: File handle for header file
        table_file: File handle for mapping table file
    """
    # Write method declaration to header (once per method)
    header_file.write(
        f"llvm::Value *{method}(const DatumPtr &node, RequestReturnType returnType);\n"
    )
    
    # Write mapping entries to table (one per command name)
    for entry in entries:
        name, min_params, default_params, max_params, return_type = entry
        return_type_ext = string_to_enum(return_type)
        string_name = name_to_cpp_identifier(name)
        
        table_file.write(
            f"stringToCmd[{NAMESPACE_NAME}::{string_name}()] = "
            f"{{&Compiler::{method}, {min_params}, {default_params}, "
            f"{max_params}, {return_type_ext}}};\n"
        )


def main():
    """Main execution function."""
    project_root = get_project_root()
    
    # Get file paths
    header_path = os.path.join(project_root, PRIMITIVE_HEADER)
    table_path = os.path.join(project_root, PRIMITIVE_MAPPINGS)
    
    print(f"Opening '{header_path}'")
    print(f"Opening '{table_path}'")
    
    # Parse all source files
    all_commands = parse_all_sources(project_root)
    
    # Open output files
    with open(header_path, 'w') as header_file, \
         open(table_path, 'w') as table_file:
        
        # Write headers
        header_file.write(GLOBAL_HEADER)
        table_file.write(GLOBAL_HEADER)
        header_file.write(PRIMITIVE_HEADER_HEADER)
        table_file.write(PRIMITIVE_MAPPINGS_HEADER)
        
        # Write all entries
        for entries, method in all_commands:
            write_primitive_entries(entries, method, header_file, table_file)
        
        # Write footers
        header_file.write(PRIMITIVE_HEADER_FOOTER)
        table_file.write(PRIMITIVE_MAPPINGS_FOOTER)
        header_file.write(GLOBAL_FOOTER)
        table_file.write(GLOBAL_FOOTER)
    
    print(f"Finished! Generated primitive mappings for {len(all_commands)} methods.")


if __name__ == "__main__":
    main()
