#! /usr/bin/env python3

"""
Generate C++ header and implementation files for QLogo command string constants.

This script generates the string constant files used for internationalization:
- include/cmd_strings.h (declarations)
- qlogo/parser/cmd_strings.cpp (definitions)

Usage:
    generate_string_constants.py
"""

import os
import sys

# Import shared parsing module
from command_parser import (
    get_project_root,
    parse_all_sources,
    name_to_cpp_identifier,
)


# ============================================================================
# Configuration
# ============================================================================

CMD_STRING_DECLARATIONS = "include/cmd_strings.h"
CMD_STRING_DEFINITIONS = "qlogo/parser/cmd_strings.cpp"
NAMESPACE_NAME = "StringConstants"


# ============================================================================
# File Templates
# ============================================================================

GLOBAL_HEADER = """// DO NOT EDIT THIS FILE!!!

// It was generated by generate_string_constants.py. Any edits to this file will
// not survive long.
"""

GLOBAL_FOOTER = """
"""

CMD_STRINGS_DECLARATIONS_HEADER = f"""#ifndef CMD_STRINGS_H
#define CMD_STRINGS_H
#include <QString>

namespace {NAMESPACE_NAME}
{{
"""

CMD_STRINGS_DECLARATIONS_FOOTER = f"""}} // namespace {NAMESPACE_NAME}
#endif // CMD_STRINGS_H
"""

CMD_STRINGS_DEFINITIONS_HEADER = """#include "cmd_strings.h"
#include <QObject>

"""

CMD_STRINGS_DEFINITIONS_FOOTER = """
"""


# ============================================================================
# Generation Functions
# ============================================================================

def write_string_entries(entries, string_header_file, string_table_file):
    """
    Write string constant entries to both output files.
    
    Args:
        entries: List of command entry tuples [name, min, default, max, return_type]
        string_header_file: File handle for header file
        string_table_file: File handle for implementation file
    """
    for entry in entries:
        name = entry[0]  # Command name
        string_name = name_to_cpp_identifier(name)
        
        # Write declaration to header
        string_header_file.write(f"const QString &{string_name}();\n")
        
        # Write definition to implementation
        string_table_file.write(f"""
    const QString &{NAMESPACE_NAME}::{string_name}()
    {{
        static const QString str = QObject::tr("{name}");
        return str;
    }}
        """)


def main():
    """Main execution function."""
    project_root = get_project_root()
    
    # Get file paths
    header_path = os.path.join(project_root, CMD_STRING_DECLARATIONS)
    impl_path = os.path.join(project_root, CMD_STRING_DEFINITIONS)
    
    print(f"Opening '{header_path}'")
    print(f"Opening '{impl_path}'")
    
    # Parse all source files
    all_commands = parse_all_sources(project_root)
    
    # Open output files
    with open(header_path, 'w') as header_file, \
         open(impl_path, 'w') as impl_file:
        
        # Write headers
        header_file.write(GLOBAL_HEADER)
        impl_file.write(GLOBAL_HEADER)
        header_file.write(CMD_STRINGS_DECLARATIONS_HEADER)
        impl_file.write(CMD_STRINGS_DEFINITIONS_HEADER)
        
        # Write all entries
        for entries, method in all_commands:
            write_string_entries(entries, header_file, impl_file)
        
        # Write footers
        header_file.write(CMD_STRINGS_DECLARATIONS_FOOTER)
        impl_file.write(CMD_STRINGS_DEFINITIONS_FOOTER)
        header_file.write(GLOBAL_FOOTER)
        impl_file.write(GLOBAL_FOOTER)
    
    print(f"Finished! Generated string constants for {len(all_commands)} methods.")


if __name__ == "__main__":
    main()
