// DO NOT EDIT THIS FILE!!!

// It was generated by generate_string_constants.py. Any edits to this file will
// not survive long.
#include "cmd_strings.h"
#include <QObject>

const QString &StringConstants::cmdStrARCTAN()
{
    static const QString str = QObject::tr("ARCTAN");
    return str;
}

const QString &StringConstants::cmdStrASHIFT()
{
    static const QString str = QObject::tr("ASHIFT");
    return str;
}

const QString &StringConstants::cmdStrLSHIFT()
{
    static const QString str = QObject::tr("LSHIFT");
    return str;
}

const QString &StringConstants::cmdStrBITAND()
{
    static const QString str = QObject::tr("BITAND");
    return str;
}

const QString &StringConstants::cmdStrBITOR()
{
    static const QString str = QObject::tr("BITOR");
    return str;
}

const QString &StringConstants::cmdStrBITXOR()
{
    static const QString str = QObject::tr("BITXOR");
    return str;
}

const QString &StringConstants::cmdStrBITNOT()
{
    static const QString str = QObject::tr("BITNOT");
    return str;
}

const QString &StringConstants::cmdStrMODULO()
{
    static const QString str = QObject::tr("MODULO");
    return str;
}

const QString &StringConstants::cmdStrSQRT()
{
    static const QString str = QObject::tr("SQRT");
    return str;
}

const QString &StringConstants::cmdStrPOWER()
{
    static const QString str = QObject::tr("POWER");
    return str;
}

const QString &StringConstants::cmdStrMINUS()
{
    static const QString str = QObject::tr("MINUS");
    return str;
}

const QString &StringConstants::cmdStr_m_()
{
    static const QString str = QObject::tr("-");
    return str;
}

const QString &StringConstants::cmdStrPRODUCT()
{
    static const QString str = QObject::tr("PRODUCT");
    return str;
}

const QString &StringConstants::cmdStrSUM()
{
    static const QString str = QObject::tr("SUM");
    return str;
}

const QString &StringConstants::cmdStrDIFFERENCE()
{
    static const QString str = QObject::tr("DIFFERENCE");
    return str;
}

const QString &StringConstants::cmdStrQUOTIENT()
{
    static const QString str = QObject::tr("QUOTIENT");
    return str;
}

const QString &StringConstants::cmdStrREMAINDER()
{
    static const QString str = QObject::tr("REMAINDER");
    return str;
}

const QString &StringConstants::cmdStrSIN()
{
    static const QString str = QObject::tr("SIN");
    return str;
}

const QString &StringConstants::cmdStrINT()
{
    static const QString str = QObject::tr("INT");
    return str;
}

const QString &StringConstants::cmdStrROUND()
{
    static const QString str = QObject::tr("ROUND");
    return str;
}

const QString &StringConstants::cmdStrEXP()
{
    static const QString str = QObject::tr("EXP");
    return str;
}

const QString &StringConstants::cmdStrLOG10()
{
    static const QString str = QObject::tr("LOG10");
    return str;
}

const QString &StringConstants::cmdStrLN()
{
    static const QString str = QObject::tr("LN");
    return str;
}

const QString &StringConstants::cmdStrRADSIN()
{
    static const QString str = QObject::tr("RADSIN");
    return str;
}

const QString &StringConstants::cmdStrRADCOS()
{
    static const QString str = QObject::tr("RADCOS");
    return str;
}

const QString &StringConstants::cmdStrRADARCTAN()
{
    static const QString str = QObject::tr("RADARCTAN");
    return str;
}

const QString &StringConstants::cmdStrCOS()
{
    static const QString str = QObject::tr("COS");
    return str;
}

const QString &StringConstants::cmdStrLESSP()
{
    static const QString str = QObject::tr("LESSP");
    return str;
}

const QString &StringConstants::cmdStrLESS_Q()
{
    static const QString str = QObject::tr("LESS?");
    return str;
}

const QString &StringConstants::cmdStrGREATERP()
{
    static const QString str = QObject::tr("GREATERP");
    return str;
}

const QString &StringConstants::cmdStrGREATER_Q()
{
    static const QString str = QObject::tr("GREATER?");
    return str;
}

const QString &StringConstants::cmdStrLESSEQUALP()
{
    static const QString str = QObject::tr("LESSEQUALP");
    return str;
}

const QString &StringConstants::cmdStrLESSEQUAL_Q()
{
    static const QString str = QObject::tr("LESSEQUAL?");
    return str;
}

const QString &StringConstants::cmdStrGREATEREQUALP()
{
    static const QString str = QObject::tr("GREATEREQUALP");
    return str;
}

const QString &StringConstants::cmdStrGREATEREQUAL_Q()
{
    static const QString str = QObject::tr("GREATEREQUAL?");
    return str;
}

const QString &StringConstants::cmdStrNOT()
{
    static const QString str = QObject::tr("NOT");
    return str;
}

const QString &StringConstants::cmdStrRANDOM()
{
    static const QString str = QObject::tr("RANDOM");
    return str;
}

const QString &StringConstants::cmdStrRERANDOM()
{
    static const QString str = QObject::tr("RERANDOM");
    return str;
}

const QString &StringConstants::cmdStrFORM()
{
    static const QString str = QObject::tr("FORM");
    return str;
}

const QString &StringConstants::cmdStr_p_()
{
    static const QString str = QObject::tr("+");
    return str;
}

const QString &StringConstants::cmdStr_star_()
{
    static const QString str = QObject::tr("*");
    return str;
}

const QString &StringConstants::cmdStr_slash_()
{
    static const QString str = QObject::tr("/");
    return str;
}

const QString &StringConstants::cmdStr_lt_()
{
    static const QString str = QObject::tr("<");
    return str;
}

const QString &StringConstants::cmdStr_gt_()
{
    static const QString str = QObject::tr(">");
    return str;
}

const QString &StringConstants::cmdStr_eq_()
{
    static const QString str = QObject::tr("=");
    return str;
}

const QString &StringConstants::cmdStr_lt__eq_()
{
    static const QString str = QObject::tr("<=");
    return str;
}

const QString &StringConstants::cmdStr_gt__eq_()
{
    static const QString str = QObject::tr(">=");
    return str;
}

const QString &StringConstants::cmdStr_lt__gt_()
{
    static const QString str = QObject::tr("<>");
    return str;
}

const QString &StringConstants::cmdStrAND()
{
    static const QString str = QObject::tr("AND");
    return str;
}

const QString &StringConstants::cmdStrOR()
{
    static const QString str = QObject::tr("OR");
    return str;
}

const QString &StringConstants::cmdStrPRINT()
{
    static const QString str = QObject::tr("PRINT");
    return str;
}

const QString &StringConstants::cmdStrPR()
{
    static const QString str = QObject::tr("PR");
    return str;
}

const QString &StringConstants::cmdStrSHOW()
{
    static const QString str = QObject::tr("SHOW");
    return str;
}

const QString &StringConstants::cmdStrTYPE()
{
    static const QString str = QObject::tr("TYPE");
    return str;
}

const QString &StringConstants::cmdStrIF()
{
    static const QString str = QObject::tr("IF");
    return str;
}

const QString &StringConstants::cmdStrIFELSE()
{
    static const QString str = QObject::tr("IFELSE");
    return str;
}

const QString &StringConstants::cmdStrRUN()
{
    static const QString str = QObject::tr("RUN");
    return str;
}

const QString &StringConstants::cmdStrREPEAT()
{
    static const QString str = QObject::tr("REPEAT");
    return str;
}

const QString &StringConstants::cmdStrREPCOUNT()
{
    static const QString str = QObject::tr("REPCOUNT");
    return str;
}

const QString &StringConstants::cmdStrBYE()
{
    static const QString str = QObject::tr("BYE");
    return str;
}

const QString &StringConstants::cmdStrOUTPUT()
{
    static const QString str = QObject::tr("OUTPUT");
    return str;
}

const QString &StringConstants::cmdStrOP()
{
    static const QString str = QObject::tr("OP");
    return str;
}

const QString &StringConstants::cmdStrSTOP()
{
    static const QString str = QObject::tr("STOP");
    return str;
}

const QString &StringConstants::cmdStr_dot_MAYBEOUTPUT()
{
    static const QString str = QObject::tr(".MAYBEOUTPUT");
    return str;
}

const QString &StringConstants::cmdStrTAG()
{
    static const QString str = QObject::tr("TAG");
    return str;
}

const QString &StringConstants::cmdStrGOTO()
{
    static const QString str = QObject::tr("GOTO");
    return str;
}

const QString &StringConstants::cmdStrCATCH()
{
    static const QString str = QObject::tr("CATCH");
    return str;
}

const QString &StringConstants::cmdStrTHROW()
{
    static const QString str = QObject::tr("THROW");
    return str;
}

const QString &StringConstants::cmdStrERROR()
{
    static const QString str = QObject::tr("ERROR");
    return str;
}

const QString &StringConstants::cmdStrPAUSE()
{
    static const QString str = QObject::tr("PAUSE");
    return str;
}

const QString &StringConstants::cmdStrCONTINUE()
{
    static const QString str = QObject::tr("CONTINUE");
    return str;
}

const QString &StringConstants::cmdStrCO()
{
    static const QString str = QObject::tr("CO");
    return str;
}

const QString &StringConstants::cmdStrRUNRESULT()
{
    static const QString str = QObject::tr("RUNRESULT");
    return str;
}

const QString &StringConstants::cmdStrFOREVER()
{
    static const QString str = QObject::tr("FOREVER");
    return str;
}

const QString &StringConstants::cmdStrTEST()
{
    static const QString str = QObject::tr("TEST");
    return str;
}

const QString &StringConstants::cmdStrIFTRUE()
{
    static const QString str = QObject::tr("IFTRUE");
    return str;
}

const QString &StringConstants::cmdStrIFT()
{
    static const QString str = QObject::tr("IFT");
    return str;
}

const QString &StringConstants::cmdStrIFFALSE()
{
    static const QString str = QObject::tr("IFFALSE");
    return str;
}

const QString &StringConstants::cmdStrIFF()
{
    static const QString str = QObject::tr("IFF");
    return str;
}

const QString &StringConstants::cmdStrEQUALP()
{
    static const QString str = QObject::tr("EQUALP");
    return str;
}

const QString &StringConstants::cmdStrEQUAL_Q()
{
    static const QString str = QObject::tr("EQUAL?");
    return str;
}

const QString &StringConstants::cmdStrNOTEQUALP()
{
    static const QString str = QObject::tr("NOTEQUALP");
    return str;
}

const QString &StringConstants::cmdStrNOTEQUAL_Q()
{
    static const QString str = QObject::tr("NOTEQUAL?");
    return str;
}

const QString &StringConstants::cmdStrWORD()
{
    static const QString str = QObject::tr("WORD");
    return str;
}

const QString &StringConstants::cmdStrLIST()
{
    static const QString str = QObject::tr("LIST");
    return str;
}

const QString &StringConstants::cmdStrSENTENCE()
{
    static const QString str = QObject::tr("SENTENCE");
    return str;
}

const QString &StringConstants::cmdStrSE()
{
    static const QString str = QObject::tr("SE");
    return str;
}

const QString &StringConstants::cmdStrFPUT()
{
    static const QString str = QObject::tr("FPUT");
    return str;
}

const QString &StringConstants::cmdStrLPUT()
{
    static const QString str = QObject::tr("LPUT");
    return str;
}

const QString &StringConstants::cmdStrARRAY()
{
    static const QString str = QObject::tr("ARRAY");
    return str;
}

const QString &StringConstants::cmdStrLISTTOARRAY()
{
    static const QString str = QObject::tr("LISTTOARRAY");
    return str;
}

const QString &StringConstants::cmdStrARRAYTOLIST()
{
    static const QString str = QObject::tr("ARRAYTOLIST");
    return str;
}

const QString &StringConstants::cmdStrFIRST()
{
    static const QString str = QObject::tr("FIRST");
    return str;
}

const QString &StringConstants::cmdStrLAST()
{
    static const QString str = QObject::tr("LAST");
    return str;
}

const QString &StringConstants::cmdStrBUTFIRST()
{
    static const QString str = QObject::tr("BUTFIRST");
    return str;
}

const QString &StringConstants::cmdStrBF()
{
    static const QString str = QObject::tr("BF");
    return str;
}

const QString &StringConstants::cmdStrBUTLAST()
{
    static const QString str = QObject::tr("BUTLAST");
    return str;
}

const QString &StringConstants::cmdStrBL()
{
    static const QString str = QObject::tr("BL");
    return str;
}

const QString &StringConstants::cmdStrITEM()
{
    static const QString str = QObject::tr("ITEM");
    return str;
}

const QString &StringConstants::cmdStrSETITEM()
{
    static const QString str = QObject::tr("SETITEM");
    return str;
}

const QString &StringConstants::cmdStr_dot_SETITEM()
{
    static const QString str = QObject::tr(".SETITEM");
    return str;
}

const QString &StringConstants::cmdStr_dot_SETFIRST()
{
    static const QString str = QObject::tr(".SETFIRST");
    return str;
}

const QString &StringConstants::cmdStr_dot_SETBF()
{
    static const QString str = QObject::tr(".SETBF");
    return str;
}

const QString &StringConstants::cmdStrWORDP()
{
    static const QString str = QObject::tr("WORDP");
    return str;
}

const QString &StringConstants::cmdStrWORD_Q()
{
    static const QString str = QObject::tr("WORD?");
    return str;
}

const QString &StringConstants::cmdStrARRAYP()
{
    static const QString str = QObject::tr("ARRAYP");
    return str;
}

const QString &StringConstants::cmdStrARRAY_Q()
{
    static const QString str = QObject::tr("ARRAY?");
    return str;
}

const QString &StringConstants::cmdStrLISTP()
{
    static const QString str = QObject::tr("LISTP");
    return str;
}

const QString &StringConstants::cmdStrLIST_Q()
{
    static const QString str = QObject::tr("LIST?");
    return str;
}

const QString &StringConstants::cmdStrEMPTYP()
{
    static const QString str = QObject::tr("EMPTYP");
    return str;
}

const QString &StringConstants::cmdStrEMPTY_Q()
{
    static const QString str = QObject::tr("EMPTY?");
    return str;
}

const QString &StringConstants::cmdStrBEFOREP()
{
    static const QString str = QObject::tr("BEFOREP");
    return str;
}

const QString &StringConstants::cmdStrBEFORE_Q()
{
    static const QString str = QObject::tr("BEFORE?");
    return str;
}

const QString &StringConstants::cmdStr_dot_EQ()
{
    static const QString str = QObject::tr(".EQ");
    return str;
}

const QString &StringConstants::cmdStrMEMBERP()
{
    static const QString str = QObject::tr("MEMBERP");
    return str;
}

const QString &StringConstants::cmdStrMEMBER_Q()
{
    static const QString str = QObject::tr("MEMBER?");
    return str;
}

const QString &StringConstants::cmdStrSUBSTRINGP()
{
    static const QString str = QObject::tr("SUBSTRINGP");
    return str;
}

const QString &StringConstants::cmdStrSUBSTRING_Q()
{
    static const QString str = QObject::tr("SUBSTRING?");
    return str;
}

const QString &StringConstants::cmdStrNUMBERP()
{
    static const QString str = QObject::tr("NUMBERP");
    return str;
}

const QString &StringConstants::cmdStrNUMBER_Q()
{
    static const QString str = QObject::tr("NUMBER?");
    return str;
}

const QString &StringConstants::cmdStrVBARREDP()
{
    static const QString str = QObject::tr("VBARREDP");
    return str;
}

const QString &StringConstants::cmdStrVBARRED_Q()
{
    static const QString str = QObject::tr("VBARRED?");
    return str;
}

const QString &StringConstants::cmdStrCOUNT()
{
    static const QString str = QObject::tr("COUNT");
    return str;
}

const QString &StringConstants::cmdStrASCII()
{
    static const QString str = QObject::tr("ASCII");
    return str;
}

const QString &StringConstants::cmdStrRAWASCII()
{
    static const QString str = QObject::tr("RAWASCII");
    return str;
}

const QString &StringConstants::cmdStrCHAR()
{
    static const QString str = QObject::tr("CHAR");
    return str;
}

const QString &StringConstants::cmdStrMEMBER()
{
    static const QString str = QObject::tr("MEMBER");
    return str;
}

const QString &StringConstants::cmdStrLOWERCASE()
{
    static const QString str = QObject::tr("LOWERCASE");
    return str;
}

const QString &StringConstants::cmdStrUPPERCASE()
{
    static const QString str = QObject::tr("UPPERCASE");
    return str;
}

const QString &StringConstants::cmdStrSTANDOUT()
{
    static const QString str = QObject::tr("STANDOUT");
    return str;
}

const QString &StringConstants::cmdStrPARSE()
{
    static const QString str = QObject::tr("PARSE");
    return str;
}

const QString &StringConstants::cmdStrRUNPARSE()
{
    static const QString str = QObject::tr("RUNPARSE");
    return str;
}

const QString &StringConstants::cmdStrFORWARD()
{
    static const QString str = QObject::tr("FORWARD");
    return str;
}

const QString &StringConstants::cmdStrFD()
{
    static const QString str = QObject::tr("FD");
    return str;
}

const QString &StringConstants::cmdStrBACK()
{
    static const QString str = QObject::tr("BACK");
    return str;
}

const QString &StringConstants::cmdStrBK()
{
    static const QString str = QObject::tr("BK");
    return str;
}

const QString &StringConstants::cmdStrLEFT()
{
    static const QString str = QObject::tr("LEFT");
    return str;
}

const QString &StringConstants::cmdStrLT()
{
    static const QString str = QObject::tr("LT");
    return str;
}

const QString &StringConstants::cmdStrRIGHT()
{
    static const QString str = QObject::tr("RIGHT");
    return str;
}

const QString &StringConstants::cmdStrRT()
{
    static const QString str = QObject::tr("RT");
    return str;
}

const QString &StringConstants::cmdStrSETXY()
{
    static const QString str = QObject::tr("SETXY");
    return str;
}

const QString &StringConstants::cmdStrSETX()
{
    static const QString str = QObject::tr("SETX");
    return str;
}

const QString &StringConstants::cmdStrSETY()
{
    static const QString str = QObject::tr("SETY");
    return str;
}

const QString &StringConstants::cmdStrSETPOS()
{
    static const QString str = QObject::tr("SETPOS");
    return str;
}

const QString &StringConstants::cmdStrSETHEADING()
{
    static const QString str = QObject::tr("SETHEADING");
    return str;
}

const QString &StringConstants::cmdStrSETH()
{
    static const QString str = QObject::tr("SETH");
    return str;
}

const QString &StringConstants::cmdStrHOME()
{
    static const QString str = QObject::tr("HOME");
    return str;
}

const QString &StringConstants::cmdStrARC()
{
    static const QString str = QObject::tr("ARC");
    return str;
}

const QString &StringConstants::cmdStrPOS()
{
    static const QString str = QObject::tr("POS");
    return str;
}

const QString &StringConstants::cmdStrHEADING()
{
    static const QString str = QObject::tr("HEADING");
    return str;
}

const QString &StringConstants::cmdStrTOWARDS()
{
    static const QString str = QObject::tr("TOWARDS");
    return str;
}

const QString &StringConstants::cmdStrSCRUNCH()
{
    static const QString str = QObject::tr("SCRUNCH");
    return str;
}

const QString &StringConstants::cmdStrSHOWTURTLE()
{
    static const QString str = QObject::tr("SHOWTURTLE");
    return str;
}

const QString &StringConstants::cmdStrST()
{
    static const QString str = QObject::tr("ST");
    return str;
}

const QString &StringConstants::cmdStrHIDETURTLE()
{
    static const QString str = QObject::tr("HIDETURTLE");
    return str;
}

const QString &StringConstants::cmdStrHT()
{
    static const QString str = QObject::tr("HT");
    return str;
}

const QString &StringConstants::cmdStrCLEAN()
{
    static const QString str = QObject::tr("CLEAN");
    return str;
}

const QString &StringConstants::cmdStrCLEARSCREEN()
{
    static const QString str = QObject::tr("CLEARSCREEN");
    return str;
}

const QString &StringConstants::cmdStrCS()
{
    static const QString str = QObject::tr("CS");
    return str;
}

const QString &StringConstants::cmdStrWRAP()
{
    static const QString str = QObject::tr("WRAP");
    return str;
}

const QString &StringConstants::cmdStrWINDOW()
{
    static const QString str = QObject::tr("WINDOW");
    return str;
}

const QString &StringConstants::cmdStrFENCE()
{
    static const QString str = QObject::tr("FENCE");
    return str;
}

const QString &StringConstants::cmdStrBOUNDS()
{
    static const QString str = QObject::tr("BOUNDS");
    return str;
}

const QString &StringConstants::cmdStrSETBOUNDS()
{
    static const QString str = QObject::tr("SETBOUNDS");
    return str;
}

const QString &StringConstants::cmdStrFILLED()
{
    static const QString str = QObject::tr("FILLED");
    return str;
}

const QString &StringConstants::cmdStrLABEL()
{
    static const QString str = QObject::tr("LABEL");
    return str;
}

const QString &StringConstants::cmdStrSETLABELHEIGHT()
{
    static const QString str = QObject::tr("SETLABELHEIGHT");
    return str;
}

const QString &StringConstants::cmdStrTEXTSCREEN()
{
    static const QString str = QObject::tr("TEXTSCREEN");
    return str;
}

const QString &StringConstants::cmdStrTS()
{
    static const QString str = QObject::tr("TS");
    return str;
}

const QString &StringConstants::cmdStrFULLSCREEN()
{
    static const QString str = QObject::tr("FULLSCREEN");
    return str;
}

const QString &StringConstants::cmdStrFS()
{
    static const QString str = QObject::tr("FS");
    return str;
}

const QString &StringConstants::cmdStrSPLITSCREEN()
{
    static const QString str = QObject::tr("SPLITSCREEN");
    return str;
}

const QString &StringConstants::cmdStrSS()
{
    static const QString str = QObject::tr("SS");
    return str;
}

const QString &StringConstants::cmdStrSETSCRUNCH()
{
    static const QString str = QObject::tr("SETSCRUNCH");
    return str;
}

const QString &StringConstants::cmdStrSHOWNP()
{
    static const QString str = QObject::tr("SHOWNP");
    return str;
}

const QString &StringConstants::cmdStrSHOWN_Q()
{
    static const QString str = QObject::tr("SHOWN?");
    return str;
}

const QString &StringConstants::cmdStrSCREENMODE()
{
    static const QString str = QObject::tr("SCREENMODE");
    return str;
}

const QString &StringConstants::cmdStrTURTLEMODE()
{
    static const QString str = QObject::tr("TURTLEMODE");
    return str;
}

const QString &StringConstants::cmdStrLABELSIZE()
{
    static const QString str = QObject::tr("LABELSIZE");
    return str;
}

const QString &StringConstants::cmdStrPENDOWN()
{
    static const QString str = QObject::tr("PENDOWN");
    return str;
}

const QString &StringConstants::cmdStrPD()
{
    static const QString str = QObject::tr("PD");
    return str;
}

const QString &StringConstants::cmdStrPENUP()
{
    static const QString str = QObject::tr("PENUP");
    return str;
}

const QString &StringConstants::cmdStrPU()
{
    static const QString str = QObject::tr("PU");
    return str;
}

const QString &StringConstants::cmdStrPENPAINT()
{
    static const QString str = QObject::tr("PENPAINT");
    return str;
}

const QString &StringConstants::cmdStrPPT()
{
    static const QString str = QObject::tr("PPT");
    return str;
}

const QString &StringConstants::cmdStrPENERASE()
{
    static const QString str = QObject::tr("PENERASE");
    return str;
}

const QString &StringConstants::cmdStrPE()
{
    static const QString str = QObject::tr("PE");
    return str;
}

const QString &StringConstants::cmdStrPENREVERSE()
{
    static const QString str = QObject::tr("PENREVERSE");
    return str;
}

const QString &StringConstants::cmdStrPX()
{
    static const QString str = QObject::tr("PX");
    return str;
}

const QString &StringConstants::cmdStrSETPENCOLOR()
{
    static const QString str = QObject::tr("SETPENCOLOR");
    return str;
}

const QString &StringConstants::cmdStrSETPC()
{
    static const QString str = QObject::tr("SETPC");
    return str;
}

const QString &StringConstants::cmdStrALLCOLORS()
{
    static const QString str = QObject::tr("ALLCOLORS");
    return str;
}

const QString &StringConstants::cmdStrSETPALETTE()
{
    static const QString str = QObject::tr("SETPALETTE");
    return str;
}

const QString &StringConstants::cmdStrSETPENSIZE()
{
    static const QString str = QObject::tr("SETPENSIZE");
    return str;
}

const QString &StringConstants::cmdStrSETBACKGROUND()
{
    static const QString str = QObject::tr("SETBACKGROUND");
    return str;
}

const QString &StringConstants::cmdStrSETBG()
{
    static const QString str = QObject::tr("SETBG");
    return str;
}

const QString &StringConstants::cmdStrPENDOWNP()
{
    static const QString str = QObject::tr("PENDOWNP");
    return str;
}

const QString &StringConstants::cmdStrPENDOWN_Q()
{
    static const QString str = QObject::tr("PENDOWN?");
    return str;
}

const QString &StringConstants::cmdStrPENMODE()
{
    static const QString str = QObject::tr("PENMODE");
    return str;
}

const QString &StringConstants::cmdStrPENCOLOR()
{
    static const QString str = QObject::tr("PENCOLOR");
    return str;
}

const QString &StringConstants::cmdStrPC()
{
    static const QString str = QObject::tr("PC");
    return str;
}

const QString &StringConstants::cmdStrPALETTE()
{
    static const QString str = QObject::tr("PALETTE");
    return str;
}

const QString &StringConstants::cmdStrPENSIZE()
{
    static const QString str = QObject::tr("PENSIZE");
    return str;
}

const QString &StringConstants::cmdStrBACKGROUND()
{
    static const QString str = QObject::tr("BACKGROUND");
    return str;
}

const QString &StringConstants::cmdStrBG()
{
    static const QString str = QObject::tr("BG");
    return str;
}

const QString &StringConstants::cmdStrSAVEPICT()
{
    static const QString str = QObject::tr("SAVEPICT");
    return str;
}

const QString &StringConstants::cmdStrSVGPICT()
{
    static const QString str = QObject::tr("SVGPICT");
    return str;
}

const QString &StringConstants::cmdStrLOADPICT()
{
    static const QString str = QObject::tr("LOADPICT");
    return str;
}

const QString &StringConstants::cmdStrMOUSEPOS()
{
    static const QString str = QObject::tr("MOUSEPOS");
    return str;
}

const QString &StringConstants::cmdStrCLICKPOS()
{
    static const QString str = QObject::tr("CLICKPOS");
    return str;
}

const QString &StringConstants::cmdStrBUTTONP()
{
    static const QString str = QObject::tr("BUTTONP");
    return str;
}

const QString &StringConstants::cmdStrBUTTON_Q()
{
    static const QString str = QObject::tr("BUTTON?");
    return str;
}

const QString &StringConstants::cmdStrBUTTON()
{
    static const QString str = QObject::tr("BUTTON");
    return str;
}

const QString &StringConstants::cmdStrTO()
{
    static const QString str = QObject::tr("TO");
    return str;
}

const QString &StringConstants::cmdStr_dot_MACRO()
{
    static const QString str = QObject::tr(".MACRO");
    return str;
}

const QString &StringConstants::cmdStrMAKE()
{
    static const QString str = QObject::tr("MAKE");
    return str;
}

const QString &StringConstants::cmdStrLOCAL()
{
    static const QString str = QObject::tr("LOCAL");
    return str;
}
